add department management UI
JCanning1/com2008-info-system pull request #75
Opened 2020-11-30 19:11 UTC by alexlieu

Still need to fix the regular expression for checking that the department code is 3 characters long, doesn't contain special characters, numbers or white spaces

2020-11-30 19:19 UTC, tomsnowgb commented
The REGEX should be

`[A-Z]{3} `

2020-12-01 12:30 UTC, JCanning1 requested changes
Looks great, might be worth converting the text entered in the department code field to captials if it's not too much trouble.

2020-12-01 14:03 UTC, JCanning1 approved these changes

2020-12-01 14:59 UTC, Chris-Howkins approved these changes

2020-12-01 15:15 UTC, merged